# Generated by Django 5.1.5 on 2025-02-06 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoviesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('imdb_rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('description', models.TextField()),
                ('length', models.CharField(max_length=100)),
                ('genre', models.JSONField(default=list)),
                ('poster_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='topMoviesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, unique=True)),
                ('movies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.moviesmodel')),
            ],
        ),
    ]
