# Generated by Django 5.1.5 on 2025-02-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_moviesmodel_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topmoviesmodel',
            name='category_name',
            field=models.CharField(max_length=50),
        ),
    ]
