# Generated by Django 5.1.5 on 2025-02-06 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_remove_topmoviesmodel_movies_topmoviesmodel_movies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topmoviesmodel',
            name='movies',
        ),
        migrations.AddField(
            model_name='topmoviesmodel',
            name='movies',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movies.moviesmodel'),
            preserve_default=False,
        ),
    ]
