# Generated by Django 5.1.5 on 2025-02-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_remove_topmoviesmodel_movies_topmoviesmodel_movies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topmoviesmodel',
            name='movies',
        ),
        migrations.AddField(
            model_name='topmoviesmodel',
            name='movies',
            field=models.ManyToManyField(related_name='categories', to='movies.moviesmodel'),
        ),
    ]
