# Generated by Django 5.1.5 on 2025-02-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_movie_remove_topmoviesmodel_movies_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoviesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('imdb_rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('description', models.TextField()),
                ('length', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('poster_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='topMoviesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('movies', models.ManyToManyField(related_name='categories', to='movies.moviesmodel')),
            ],
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
