# Generated by Django 5.1.5 on 2025-02-06 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_moviesmodel_topmoviesmodel_delete_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topmoviesmodel',
            name='movies',
        ),
        migrations.AddField(
            model_name='topmoviesmodel',
            name='movies',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='movies.moviesmodel'),
        ),
    ]
