# Generated by Django 5.1.5 on 2025-02-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_remove_moviesmodel_category_moviesmodel_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviesmodel',
            name='category',
        ),
        migrations.AddField(
            model_name='topmoviesmodel',
            name='movies',
            field=models.ManyToManyField(related_name='top_movies', to='movies.moviesmodel'),
        ),
    ]
