# Generated by Django 5.1.5 on 2025-02-07 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_remove_moviesmodel_category_topmoviesmodel_movies'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenreTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_genre', models.CharField(max_length=100)),
                ('movies', models.ManyToManyField(related_name='movie_types', to='movies.moviesmodel')),
            ],
        ),
        migrations.CreateModel(
            name='GenreMoviesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.genretypemodel')),
            ],
        ),
    ]
