# Generated by Django 5.1.5 on 2025-03-03 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TorrentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField()),
                ('seeds', models.CharField(blank=True, max_length=20, null=True)),
                ('leeches', models.CharField(blank=True, max_length=20, null=True)),
                ('year', models.CharField(blank=True, max_length=10, null=True)),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
